arch:
  - amd64
  - ppc64le
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
install:
  - "pip install -U pip"
  - "pip install poetry"
  - "poetry install --no-ansi"
script:
  - "poetry run pytest"
