arch:
  - amd64
  - ppc64le
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
install:
  - "pip install -e ."
  - "pip install -U pytest"
script:
  - "pytest"
